version: "3"
services:
  cadastro-empresas-api:
    image: cadastro-empresas-api
    ports:
      - "8080:8080"
    networks:
      - cadastro-empresas-api-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - cadastro-empresas-api-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cadempresasdb

networks:
  cadastro-empresas-api-mysql: 
